openapi: 3.0.0
info:
    title: OpenAPI definition
    version: v0
servers:
    -   url: http://localhost:8080
        description: Generated server url
paths:
    /login:
        post:
            tags:
                - LoginApi
            operationId: login
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/User"
                required: true
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/TokenData"

    /test:
        get:
            tags:
                - TestApi
            operationId: test
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: string

    /users/{username}:
        get:
            tags:
                - UserApi
            operationId: getUserByUsername
            parameters:
                -   name: username
                    in: path
                    required: true
                    schema:
                        type: string
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/User"

    /users/refreshtoken:
        get:
            tags:
                - UserApi
            operationId: refreshToken
            responses:
                "200":
                    description: OK

    /users:
        get:
            tags:
                - UserApi
            operationId: getAllUsers
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/User"

        post:
            tags:
                - UserApi
            operationId: createUser
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/User"
                required: true
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/User"


components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT

    schemas:
        TokenData:
            type: object
            required:
                - accessToken
                - refreshToken
            properties:
                accessToken:
                    type: string
                refreshToken:
                    type: string

        User:
            type: object
            required:
                - username
            properties:
                id:
                    type: string
                username:
                    type: string
                password:
                    type: string
                roles:
                    type: array
                    items:
                        $ref: "#/components/schemas/RoleEnum"

        Article:
            type: object
            required:
                - headLine
                - content
            properties:
                id:
                    type: number
                headLine:
                    type: string
                content:
                    type: string
                comments:
                    type: array
                    items:
                        $ref: "#/components/schemas/Comment"

        Comment:
            type: object
            required:
                - content
            properties:
                id:
                    type: number
                content:
                    type: string

        RoleEnum:
            type: string
            enum:
                - LESER
                - AUTOR
                - MODERATOR
                - ADMIN
            x-enum-varnames:
                - LESER
                - AUTOR
                - MODERATOR
                - ADMIN
